# Generated by Django 3.2.3 on 2021-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_selectbranch',
            field=models.BooleanField(default=False),
        ),
    ]
