# Generated by Django 3.2.3 on 2021-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_selectbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_selectbranch',
            field=models.BooleanField(default=False, verbose_name='Can Select Branch'),
        ),
    ]
