# Generated by Django 3.2.3 on 2021-10-22 10:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_can_selectbranch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/default_image.png', upload_to=users.models.image_path),
        ),
    ]
