# Generated by Django 4.0.2 on 2022-02-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_editclient',
            field=models.BooleanField(default=True),
        ),
    ]
