# Generated by Django 4.0.5 on 2022-06-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_can_accessaws'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_accessclients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_accessmmaptsp2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_accessusers',
            field=models.BooleanField(default=True),
        ),
    ]
