# Generated by Django 3.2.3 on 2021-09-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaccountcode',
            old_name='Branchcode',
            new_name='branchcode',
        ),
    ]
