# Generated by Django 3.2.3 on 2021-09-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_branchcode_clientaccountcode_branchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccountcode',
            name='branchcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='Branch Code'),
        ),
    ]
