# Generated by Django 3.2.3 on 2021-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientaccountcode_clientaccountcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccountcode',
            name='clientaccountcode',
        ),
        migrations.AddField(
            model_name='clientaccountcode',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='Zip Code'),
        ),
    ]
