# Generated by Django 3.2.3 on 2021-10-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210930_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branchcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='Branch Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Client Code'),
        ),
        migrations.AddField(
            model_name='client',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='Zip Code'),
        ),
    ]
