# Generated by Django 3.2.3 on 2021-10-12 10:25

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_image',
            field=models.ImageField(default='client_pic/default_image.png', upload_to=clients.models.image_path),
        ),
    ]
