# Generated by Django 3.2.3 on 2021-10-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_client_client_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Client Code'),
        ),
    ]
