# Generated by Django 4.0.4 on 2022-05-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_client_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_isdisabled',
            field=models.BooleanField(default=False, verbose_name='Is Disabled'),
        ),
    ]
