# Generated by Django 3.2.3 on 2021-09-30 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmapid', models.IntegerField(blank=True, default=0, verbose_name='mmapid')),
                ('ben_mmap_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('mmap_clientid', models.IntegerField(blank=True, default=0, verbose_name='mmap_clientid')),
                ('client_cycle', models.IntegerField(blank=True, default=0, verbose_name='Clients Cycle ')),
                ('ben1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Beneficiary 1')),
                ('ben2', models.CharField(blank=True, max_length=80, verbose_name='Beneficiary 2')),
                ('ben3', models.CharField(blank=True, max_length=80, verbose_name='Beneficiary 3')),
                ('ben1_dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Beneficiary 1 DOB')),
                ('ben2_dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Beneficiary 2 DOB')),
                ('ben3_dob', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Beneficiary 3 DOB')),
                ('ben1_rel', models.CharField(blank=True, max_length=80, null=True, verbose_name='Beneficiary 1 Relationship')),
                ('ben2_rel', models.CharField(blank=True, max_length=80, null=True, verbose_name='Beneficiary 2 Relationship')),
                ('ben3_rel', models.CharField(blank=True, max_length=80, null=True, verbose_name='Beneficiary 3 Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='Branchcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcode', models.CharField(blank=True, default='', max_length=3, verbose_name='BranchCode')),
                ('bname', models.CharField(blank=True, max_length=150, verbose_name='BranchName')),
                ('dateadded', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date added')),
            ],
        ),
        migrations.CreateModel(
            name='Mmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(blank=True, default=0, verbose_name='ClientID')),
                ('mmap_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('mmap_sex', models.CharField(blank=True, max_length=20, verbose_name='Sex')),
                ('mmap_age', models.IntegerField(blank=True, default=0, verbose_name='Age')),
                ('mmap_type', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('mmap_branch', models.CharField(blank=True, max_length=50, verbose_name='Branch')),
                ('mmap_address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('mmap_setupdate', models.DateField(default=django.utils.timezone.now, verbose_name='Approved Date')),
                ('recuited_by', models.CharField(blank=True, max_length=50, verbose_name='Recruited by')),
                ('client_cycle', models.IntegerField(blank=True, default=0, verbose_name='Clients Cycle ')),
                ('mmap_dob', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date of Birth')),
                ('processed_by', models.CharField(blank=True, max_length=50, verbose_name='Processed by')),
                ('processed_des', models.CharField(blank=True, max_length=50, verbose_name='Processed by')),
                ('processed_date', models.DateField(default=django.utils.timezone.now, verbose_name='Processed Date')),
                ('checked_by', models.CharField(blank=True, max_length=50, verbose_name='Checked by')),
                ('checked_des', models.CharField(blank=True, max_length=50, verbose_name='Checked by')),
                ('checked_date', models.DateField(default=django.utils.timezone.now, verbose_name='Checked Date')),
                ('approved_by', models.CharField(blank=True, max_length=50, verbose_name='Approved by')),
                ('approved_des', models.CharField(blank=True, max_length=50, verbose_name='Approved by')),
                ('approved_date', models.DateField(default=django.utils.timezone.now, verbose_name='Approved Date')),
                ('branch_control_number', models.CharField(blank=True, max_length=10, verbose_name='Branch Control Number')),
                ('mmap_encodedate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='MMAP Date Encoded')),
                ('mmap_expired', models.DateField(default=django.utils.timezone.now, verbose_name='MMAP Exprired Date')),
                ('mmap_premium', models.IntegerField(default=900, verbose_name='MMAP Premium')),
                ('clientimg', models.ImageField(default='client_pic/default_image.jpg', upload_to='')),
                ('mmapservicecentercontrolno', models.CharField(default='None', max_length=10, verbose_name='MMAP Service Center Control Number')),
                ('mmapbcode', models.CharField(blank=True, default='None', max_length=3, verbose_name='MMAP Branch Code')),
            ],
        ),
        migrations.CreateModel(
            name='Sccn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmap_encodedate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='MMAP Date Encoded')),
                ('sscnservicecentercontrolno', models.CharField(blank=True, max_length=10, verbose_name='Service Center Control Number')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Client Name')),
                ('sccnbcode', models.CharField(blank=True, default='None', max_length=10, verbose_name='Branch Code')),
            ],
        ),
    ]
