# Generated by Django 3.2.3 on 2021-10-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sccn',
            name='sccnbranch',
            field=models.CharField(blank=True, default='None', max_length=15, verbose_name='SCCN Branch'),
        ),
    ]
