# Generated by Django 3.2.3 on 2021-10-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0002_sccn_sccnbranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmap',
            name='branch_control_number',
        ),
    ]
