# Generated by Django 3.2.3 on 2021-10-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0004_auto_20211005_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmap',
            name='client_code',
        ),
        migrations.AddField(
            model_name='mmap',
            name='clientid',
            field=models.IntegerField(blank=True, default=0, verbose_name='ClientID'),
        ),
    ]
