# Generated by Django 3.2.3 on 2021-10-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0005_auto_20211005_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmap',
            name='client_code',
            field=models.CharField(blank=True, default='None', max_length=15, verbose_name='MMAP Client Code'),
        ),
    ]
