# Generated by Django 3.2.3 on 2021-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0006_mmap_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmap',
            name='expired_status',
            field=models.BooleanField(default=False, verbose_name='MMAP Exprired Status'),
        ),
    ]
