# Generated by Django 3.2.3 on 2021-10-05 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0007_mmap_expired_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmap',
            name='mmap_encodedate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='MMAP Date Encoded'),
        ),
    ]
