# Generated by Django 3.2.3 on 2021-10-21 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0008_alter_mmap_mmap_encodedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sccn',
            name='mmap_expired',
            field=models.BooleanField(default=False, verbose_name='MMAP Exprired Status'),
        ),
        migrations.AddField(
            model_name='sccn',
            name='mmap_setupdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='MMAP Setup Date'),
        ),
        migrations.AlterField(
            model_name='mmap',
            name='mmap_setupdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='MMAP Setup Date'),
        ),
    ]
