# Generated by Django 3.2.8 on 2021-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0011_auto_20211021_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='mmapid',
            field=models.CharField(default='None', max_length=10, verbose_name='MMAP Service Center Control Number'),
        ),
    ]
