# Generated by Django 4.0.2 on 2022-03-01 14:18

from django.db import migrations, models
import mmaptsp2.models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0012_alter_beneficiary_mmapid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmap',
            name='mmap_form_bimage',
            field=models.ImageField(default='profile_pic/default_image.png', upload_to=mmaptsp2.models.image_path, verbose_name='MMAP Back Form'),
        ),
        migrations.AddField(
            model_name='mmap',
            name='mmap_form_fimage',
            field=models.ImageField(default='profile_pic/default_image.png', upload_to=mmaptsp2.models.image_path, verbose_name='MMAP Front Form'),
        ),
    ]
