# Generated by Django 4.0.3 on 2022-03-03 09:42

from django.db import migrations, models
import mmaptsp2.models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0013_mmap_mmap_form_bimage_mmap_mmap_form_fimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmap',
            name='mmap_form_bimage',
            field=models.ImageField(default='mmaptsp2_pic/default_image.png', upload_to=mmaptsp2.models.image_path, verbose_name='MMAP Back Form'),
        ),
        migrations.AlterField(
            model_name='mmap',
            name='mmap_form_fimage',
            field=models.ImageField(default='mmaptsp2_pic/default_image.png', upload_to=mmaptsp2.models.image_path, verbose_name='MMAP Front Form'),
        ),
    ]
