# Generated by Django 4.0.3 on 2022-03-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0014_alter_mmap_mmap_form_bimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmap',
            old_name='recuited_by',
            new_name='recruited_by',
        ),
    ]
