# Generated by Django 4.0.3 on 2022-03-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0015_rename_recuited_by_mmap_recruited_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmap',
            old_name='recruited_by',
            new_name='recuited_by',
        ),
    ]
