# Generated by Django 4.0.4 on 2022-04-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0017_alter_beneficiary_mmapid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='mmapid',
            field=models.CharField(default='None', max_length=10, verbose_name='MMAPID'),
        ),
    ]
