# Generated by Django 4.0.4 on 2022-05-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0018_alter_beneficiary_mmapid'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='mmapservicecentercontrolno',
            field=models.CharField(default='None', max_length=10, verbose_name='MMAP Service Center Control Number'),
        ),
    ]
