# Generated by Django 4.0.4 on 2022-05-07 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0019_beneficiary_mmapservicecentercontrolno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='mmapservicecentercontrolno',
            new_name='mmapservicecentercontrolno1',
        ),
    ]
