# Generated by Django 4.0.4 on 2022-05-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0022_beneficiary_mmapservicecentercontrolno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='mmapservicecentercontrolno',
        ),
    ]
