# Generated by Django 4.0.4 on 2022-05-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0023_remove_beneficiary_mmapservicecentercontrolno'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='mmapservicecentercontrolno1',
            field=models.CharField(default='None', max_length=10, verbose_name='MMAP Service Center Control Number'),
        ),
    ]
