# Generated by Django 4.0.4 on 2022-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0024_beneficiary_mmapservicecentercontrolno1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='mmapservicecentercontrolno1',
        ),
    ]
