# Generated by Django 4.0.4 on 2022-05-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0026_beneficiary_mmapservicecentercontrolno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmap',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='Is Canceled'),
        ),
    ]
