# Generated by Django 4.0.5 on 2022-06-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmaptsp2', '0027_mmap_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmap',
            name='is_canceled',
        ),
    ]
