# Generated by Django 4.0.6 on 2022-07-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(blank=True, max_length=100, verbose_name='Event Type Name')),
                ('event_description', models.TextField(blank=True, max_length=150, verbose_name='Event Description')),
            ],
        ),
    ]
