# Generated by Django 4.0.6 on 2022-07-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(auto_now=True, verbose_name='Event Date'),
        ),
    ]
