# Generated by Django 4.0.6 on 2022-07-17 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='voter_regdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registered Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='23:50', verbose_name='Event Date'),
        ),
    ]
