# Generated by Django 4.0.6 on 2022-07-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_voter_voter_regdate_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='23:17', verbose_name='Event Time'),
        ),
    ]
