# Generated by Django 4.0.6 on 2022-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='14:01', verbose_name='Event Time'),
        ),
    ]
