# Generated by Django 4.0.6 on 2022-07-27 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_event_date_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_setupDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Setup Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='11:47', verbose_name='Event Time'),
        ),
    ]
