# Generated by Django 4.0.6 on 2022-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_event_event_setupdate_alter_event_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='15:52', verbose_name='Event Time'),
        ),
    ]
