# Generated by Django 4.0.6 on 2022-08-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='eventpid',
            field=models.IntegerField(default=0, verbose_name='Event ID'),
        ),
        migrations.AddField(
            model_name='event_positions',
            name='eventpid',
            field=models.IntegerField(default=0, verbose_name='Event ID'),
        ),
        migrations.AddField(
            model_name='voter',
            name='eventpid',
            field=models.IntegerField(default=0, verbose_name='Event ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='09:04', verbose_name='Event Time'),
        ),
    ]
