# Generated by Django 4.0.6 on 2022-08-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_candidates_eventpid_event_positions_eventpid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='09:06', verbose_name='Event Time'),
        ),
    ]
