# Generated by Django 4.0.6 on 2022-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_event_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='eventpid',
            new_name='eventid',
        ),
        migrations.RenameField(
            model_name='event_positions',
            old_name='eventpid',
            new_name='eventid',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='eventpid',
            new_name='eventid',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='09:07', verbose_name='Event Time'),
        ),
    ]
