# Generated by Django 4.1 on 2022-08-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_rename_eventpid_candidates_eventid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key_var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(default=0, verbose_name='Event ID')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='15:20', verbose_name='Event Time'),
        ),
    ]
