# Generated by Django 4.1 on 2022-08-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_key_var_alter_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='key_var',
            name='eventcaption',
            field=models.CharField(blank=True, max_length=50, verbose_name='Event Caption'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='15:23', verbose_name='Event Time'),
        ),
    ]
