# Generated by Django 4.1 on 2022-08-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_key_var_eventcaption_alter_event_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='voter_regdate',
        ),
        migrations.AddField(
            model_name='candidates',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default='17:18', verbose_name='Event Time'),
        ),
    ]
