# Generated by Django 4.0.5 on 2022-06-13 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(blank=True, max_length=150, verbose_name='Account Name')),
                ('accountID', models.IntegerField(blank=True, default=0, verbose_name='Account ID')),
                ('accountUser', models.CharField(blank=True, max_length=150, verbose_name='Account User')),
                ('accessKeyID', models.CharField(blank=True, max_length=150, verbose_name='Access Key ID')),
                ('secretAccessKey', models.CharField(blank=True, max_length=150, verbose_name='Secret Access Key')),
                ('instanceName', models.CharField(blank=True, max_length=150, verbose_name='Instance Name')),
                ('instanceID', models.CharField(blank=True, max_length=150, verbose_name='Instance ID')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Region')),
                ('serverIP', models.CharField(blank=True, max_length=150, verbose_name='Server IP')),
                ('database', models.CharField(blank=True, max_length=150, verbose_name='Database')),
                ('serverType', models.CharField(blank=True, max_length=150, verbose_name='Database')),
                ('setupDate', models.DateField(default=django.utils.timezone.now, verbose_name='Setup Date')),
                ('serverSetupDate', models.DateField(default=django.utils.timezone.now, verbose_name='Setup Date')),
            ],
        ),
    ]
