# Generated by Django 4.0.5 on 2022-06-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsaccounts',
            name='instanceName',
        ),
    ]
