# Generated by Django 4.0.5 on 2022-06-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_remove_awsaccounts_instancename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='accountID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='awsaccounts',
            name='accountID',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account ID'),
        ),
    ]
