# Generated by Django 4.0.5 on 2022-06-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0006_alter_aws_accountid_alter_awsaccounts_accountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aws',
            name='serverSetupDate',
        ),
    ]
