# Generated by Django 4.0.5 on 2022-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_remove_aws_serversetupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aws',
            name='serverType',
            field=models.CharField(blank=True, max_length=150, verbose_name='Server Type'),
        ),
    ]
