# Generated by Django 4.0.5 on 2022-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_alter_aws_servertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='aws',
            name='area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Area'),
        ),
    ]
