# Generated by Django 4.0.5 on 2022-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_aws_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='aws',
            name='rdpPass',
            field=models.CharField(blank=True, max_length=150, verbose_name='RDP Password'),
        ),
    ]
