"""
Django settings for kmsystem project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'changename')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['127.0.0.1']
ALLOWED_HOSTS = []
ALLOWED_HOSTS_ENV =os.environ.get('ALLOWED_HOSTS')

if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))


# Application definition

INSTALLED_APPS = [
    'event.apps.EventConfig',
    'aws.apps.AwsConfig',
    'mmaptsp2.apps.Mmaptsp2Config',
    'users.apps.UsersConfig',
    'clients.apps.ClientsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django-session-idle-timeout',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    # 'django-session-idle-timeout.middleware.SessionIdleTimeout',
]

ROOT_URLCONF = 'kmsystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kmsystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
  'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kmsdbdev',
        'USERNAME': 'El Platitos',
        'PASSWORD': '21*antsfokly*-~9)',
        'PORT': '3306',
        'HOST': 'localhost'
     }
   
}

 # 'new': {
    #  #  'ENGINE': 'django.db.backends.sqlite3',
    #  #  'NAME': BASE_DIR / 'db.sqlite3',
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'kmsdb002',
    #  #   'USERNAME': 'ODBC',
    #  #   'PASSWORD': '21*antsfokly*-~9)',
    #     'USERNAME': 'Learner',
    #     'PASSWORD': '21*antsfokly*-~9)',
    #     'PORT': '3306',
    #     'HOST': 'localhost'
    # }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# SESSION_EXPIRE_SECONDS = 1800 #30mins Logout
SESSION_COOKIE_AGE = 1800
SESSION_TIMEOUT_REDIRECT = '/users/login'

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

DATE_INPUT_FORMATS = ['%Y-%m-%d']

# TIME_INPUT_FORMATS = ['%H:%M']

# TIME_FORMAT = ['H:i']

STATIC_URL = '/static/static/'
MEDIA_URL = '/static/media/'

AUTH_USER_MODEL = 'users.User'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# STATIC_URL = '/static/'

# MEDIA_URL = '/media/'


STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STATIC_ROOT = "/vol/web/static" 

MEDIA_ROOT = "/vol/web/media" 



# if DEBUG:
#   STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# else:
#   STATIC_ROOT = os.path.join(BASE_DIR, 'static')  

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

